include: package:very_good_analysis/analysis_options.3.0.2.yaml
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
  errors:
    invalid_annotation_target: ignore
