name: hpm_portfolio
description: My portfolio
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.13+1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.7.0
  layout: ^1.0.3
  retrofit: ^3.0.1+1
  shimmer: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.1.0+1
  url_launcher: ^6.1.6
  very_good_analysis: ^3.1.0
  widgetbook: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: TimesNewerRoman
      fonts:
        - asset: assets/fonts/TimesNewerRoman-Regular.otf
        - asset: assets/fonts/TimesNewerRoman-Italic.otf
          style: italic
        - asset: assets/fonts/TimesNewerRoman-Bold.otf
          weight: 700
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600

flutter_gen:
  integrations:
    flutter_svg: true
