name: hpm_portfolio
description: My portfolio
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.3

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_markdown: ^0.6.21
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  jiffy: ^6.2.2
  json_annotation: ^4.8.1
  layout: ^1.0.5
  loggy: ^2.0.3
  retrofit: ^4.1.0
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  shimmer: ^3.0.0
  url_launcher: ^6.2.5

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.11
  riverpod_lint:
  very_good_analysis: ^5.1.0
  widgetbook: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: TimesNewerRoman
      fonts:
        - asset: assets/fonts/TimesNewerRoman-Regular.otf
        - asset: assets/fonts/TimesNewerRoman-Italic.otf
          style: italic
        - asset: assets/fonts/TimesNewerRoman-Bold.otf
          weight: 700
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600

flutter_gen:
  integrations:
    flutter_svg: true
